### PR TITLE
#61 JsonPathParser wrongly parse unescaped numbers - fixes #61

### LINKED ISSUE #61: JsonPathParser seems to wrongly parse unescaped reference-token if its starts with a number
Hello,

First of all, I want to thank you for sharing this fork !

In the context of evaluating this fork as a replacement of unmaintained original https://github.com/java-json-tools/json-patch, I think I found an issue in the JsonPathParser

Version used:  2.0.1

simple test code : 

        String inputToPatch = "{\"5gStringToMove\":\"exists\"}";

        JsonPatchOperation operation = new MoveOperation("/5gStringToMove", "/5gStringMoved");

        var patch = new JsonPatch(List.of(operation));
        JsonNode objToBePatched = JsonLoader.fromString(inputToPatch);
        JsonNode result = null;
        try
        {
            result = patch.apply(objToBePatched);
        } catch (JsonPatchException e)
        {
            TRACER.fatal(e.getMessage(), e);
            Assertions.fail(e);
        }

The attribute name and JsonPointer towards the attribute is valid as per [RFC 6901](https://datatracker.ietf.org/doc/html/rfc6901) 
Such attribute names are quite frequent in 3GPP standards for example.

But the lib fails in converting the JsonPointer to Json Path :

com.gravity9.jsonpatch.JsonPatchException: Filter: [5]['gStringToMove'] can only be applied to arrays. Current context is: {"5gStringToMove":"exists"}
	at com.gravity9.jsonpatch.JsonPatchOperation.apply(JsonPatchOperation.java:124) ~[json-patch-path-2.0.1.jar:?]
	at com.gravity9.jsonpatch.JsonPatch.apply(JsonPatch.java:144) ~[json-patch-path-2.0.1.jar:?]
	at com.my.example.test.testMoveElementSimple(Test.java:368) ~[test-classes/:?]

The parser considered the number as an array index while it's not even a number, then it split to next char and consider another attribue name.

The issue is more or less here:
https://github.com/gravity9-tech/json-patch-path/blob/master/src/main/java/com/gravity9/jsonpatch/JsonPathParser.java#L7
and here
https://github.com/gravity9-tech/json-patch-path/blob/master/src/main/java/com/gravity9/jsonpatch/JsonPathParser.java#L27

Not sure how to fix this, though...

Original https://github.com/java-json-tools/json-patch was able to patch the same data.

Rgds
Laurent

### PR DESCRIPTION
**Pull request by MateuszGravity9**

### CODE REVIEW

File: src/main/java/com/gravity9/jsonpatch/JsonPathParser.java [hunk 1]
```diff
@@ -1,29 +1,36 @@
...
-			.replace("~0", "~") // ~ must be escaped in JsonPointer using ~0
-			.replaceAll(ARRAY_ELEMENT_REGEX, "[$1]");
-	}
+        return "$" + Arrays.stream(path.replace('/', '.')
+                        .replace("~1", "/") // / must be escaped in JsonPointer using ~1
+                        .replace("~0", "~") // ~ must be escaped in JsonPointer using ~0
+                        .split("\\."))    // split string to analyze every path  field separately
+                .filter(s -> !s.isEmpty())    // skip empty string on the beginning of the array
+                .map(s -> s.replaceAll(ARRAY_ELEMENT_REGEX, "[$1]"))
+                .reduce("", (s, s2) -> s + "." + s2);    //connect the path
```
Comment (piotrlg9) [inline src/main/java/com/gravity9/jsonpatch/JsonPathParser.java:34]: can be simplified with `.collect(Collectors.joining("."));`

File: src/main/java/com/gravity9/jsonpatch/JsonPathParser.java [hunk 2]
```diff
@@ -1,29 +1,36 @@
...
+        }
 
-		return "$" + path.replace('/', '.')
-			.replace("~1", "/") // / must be escaped in JsonPointer using ~1
-			.replace("~0", "~") // ~ must be escaped in JsonPointer using ~0
-			.replaceAll(ARRAY_ELEMENT_REGEX, "[$1]");
-	}
+        return "$" + Arrays.stream(path.replace('/', '.')
+                        .replace("~1", "/") // / must be escaped in JsonPointer using ~1
+                        .replace("~0", "~") // ~ must be escaped in JsonPointer using ~0
```
Comment (piotrlg9) [inline src/main/java/com/gravity9/jsonpatch/JsonPathParser.java:30]: are there any test cases for this escaping?

File: src/main/java/com/gravity9/jsonpatch/JsonPathParser.java [hunk 3]
```diff
@@ -1,29 +1,36 @@
...
+                        .split("\\."))    // split string to analyze every path  field separately
+                .filter(s -> !s.isEmpty())    // skip empty string on the beginning of the array
+                .map(s -> s.replaceAll(ARRAY_ELEMENT_REGEX, "[$1]"))
```
Comment (piotrlg9) [inline src/main/java/com/gravity9/jsonpatch/JsonPathParser.java:33]: please include test case with 2+ matching segments in source string, like "/data/0/123"

File: src/main/java/com/gravity9/jsonpatch/JsonPathParser.java (hunk 2 above)
Comment (MateuszGravity9) [reply src/main/java/com/gravity9/jsonpatch/JsonPathParser.java:30]: There are tests for the escaping across the project

File: src/main/java/com/gravity9/jsonpatch/JsonPathParser.java (hunk 3 above)
Comment (MateuszGravity9) [reply src/main/java/com/gravity9/jsonpatch/JsonPathParser.java:33]: Included

File: src/main/java/com/gravity9/jsonpatch/JsonPathParser.java (hunk 1 above)
Comment (MateuszGravity9) [reply src/main/java/com/gravity9/jsonpatch/JsonPathParser.java:34]: Unfortunately that works differently - we would need to add prefix in the joiner and then it will not work for the case where the path is just "/"

Comment (piotrlg9) [reply src/main/java/com/gravity9/jsonpatch/JsonPathParser.java:34]: OK, thanks

**Review by piotrlg9 — APPROVED** [review]
